In [1]:
import numpy as np

In [2]:
M = np.array([[4], [10]])
V = np.array([[4, 2], [2, 9]])
m0 = 2
l0 = 2

In [3]:
V_inv = np.linalg.inv(V)
V_inv
I = np.eye(2)

In [4]:
dsquared = np.linalg.multi_dot([(M - m0*I).T, V_inv, M - m0*I])
dsquared

array([[ 11.125,   8.75 ],
       [  8.75 ,   8.5  ]])

In [5]:
np.dot([2, 8], [[0.5], [0.5]])

array([ 5.])

In [6]:
(M - m0*I).T

array([[  2.,  10.],
       [  4.,   8.]])